apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "supersecretpassword"
  JWT_SECRET: "enterprise-production-jwt-key-2026"
  DATABASE_URL: "postgresql://postgres:supersecretpassword@postgres-service:5432/demo_db"